const defaultData = {name:'Baba Ramdev Mandir Raipur Hisar', welcome:'At Baba Ramdev Mandir Raipur Hisar, every prayer is welcome, every visitor is family, and every act of seva brings us closer together.', about:'Our mandir is a quiet corner for prayer, reflection, and community. Built with love and sustained through seva, we welcome families, elders, children, and every soul seeking a moment of stillness.', address:'4RWC+X87, Dhani Raipur, Hisar, Haryana 125044', phone:'+91 00000 00000', email:'hello@jaibabamandir.org', map:'https://maps.app.goo.gl/pNMX7ZAJRMEHQtE5A'};
const schedule = [['Mangala Aarti','5:30 AM'],['Morning Darshan','6:00 AM - 12:00 PM'],['Madhyanna Aarti','12:00 PM'],['Evening Darshan','4:00 PM - 8:30 PM'],['Shej Aarti','9:00 PM']];
let language = localStorage.getItem('jaiBabaLanguage') || 'en';
let data = JSON.parse(localStorage.getItem('jaiBabaTemple')) || defaultData;
if (data.name === 'Shri Jai Baba' || data.name === 'Shri Jai Baba Mandir') data.name = defaultData.name;
if (data.welcome && data.welcome.includes('Shri Jai Baba Mandir')) data.welcome = defaultData.welcome;
if (data.address === 'Your temple address\nCity, State, PIN' || data.address === 'Your temple addressCity, State, PIN') data.address = defaultData.address;
const $ = id => document.getElementById(id);
function render(){ $('brandName').textContent=data.name; $('footerName').textContent=data.name; $('heroCopy').textContent=language==='hi'?'बाबा रामदेव मंदिर रायपुर हिसार में हर प्रार्थना का स्वागत है, हर आगंतुक हमारा परिवार है और सेवा का हर कार्य हमें एक-दूसरे के करीब लाता है।':data.welcome; $('aboutCopy').textContent=language==='hi'?'हमारा मंदिर प्रार्थना, आत्मचिंतन और समुदाय के लिए एक शांत स्थान है। सेवा और प्रेम से बना यह स्थान हर उस व्यक्ति का स्वागत करता है जो शांति का एक पल खोज रहा है।':data.about; $('address').innerHTML=data.address.replace(/\n/g,'<br>'); $('phone').textContent=data.phone; $('email').textContent=data.email; $('mapLink').href=data.map; $('schedule').innerHTML=schedule.map(([label,time],index)=>`<div class="schedule-row"><strong>${language==='hi'?['मंगला आरती','प्रातः दर्शन','मध्याह्न आरती','संध्या दर्शन','शयन आरती'][index]:label}</strong><span>${time}</span></div>`).join(''); }
function openPanel(){ $('overlay').classList.add('active'); $('adminPanel').classList.add('open'); $('adminPanel').setAttribute('aria-hidden','false'); }
function closePanel(){ $('overlay').classList.remove('active'); $('adminPanel').classList.remove('open'); $('adminPanel').setAttribute('aria-hidden','true'); }
function showEditor(){ $('loginView').hidden=true; $('editorView').hidden=false; $('editName').value=data.name; $('editWelcome').value=data.welcome; $('editAbout').value=data.about; $('editAddress').value=data.address; $('editPhone').value=data.phone; $('editEmail').value=data.email; $('editMap').value=data.map; }
$('schedule').innerHTML=''; render();
$('adminOpen').addEventListener('click',openPanel); $('adminClose').addEventListener('click',closePanel); $('overlay').addEventListener('click',closePanel); $('menuToggle').addEventListener('click',()=>document.querySelector('.desktop-nav').classList.toggle('mobile-open')); document.querySelectorAll('.desktop-nav a').forEach(link=>link.addEventListener('click',()=>document.querySelector('.desktop-nav').classList.remove('mobile-open')));
$('loginForm').addEventListener('submit',event=>{event.preventDefault(); const email=$('loginEmail').value.trim().toLowerCase(); const password=$('loginPassword').value; if(email==='admin@jaibabaramdave.org'&&password==='jai baba ri'){ $('loginError').textContent=''; showEditor(); } else $('loginError').textContent='That email or password is not recognised.'; });
$('editorForm').addEventListener('submit',event=>{event.preventDefault(); data={name:$('editName').value.trim(),welcome:$('editWelcome').value.trim(),about:$('editAbout').value.trim(),address:$('editAddress').value.trim(),phone:$('editPhone').value.trim(),email:$('editEmail').value.trim(),map:$('editMap').value.trim()}; localStorage.setItem('jaiBabaTemple',JSON.stringify(data)); render(); $('saveStatus').textContent='Changes saved to this browser.'; setTimeout(()=>$('saveStatus').textContent='',3000); });
$('logoutButton').addEventListener('click',()=>{ $('editorView').hidden=true; $('loginView').hidden=false; $('loginForm').reset(); });
const translations = {en:{top:'Open daily 5:30 AM - 9:00 PM',nav:['About','Darshan','Seva','Visit us'],admin:'◈ Admin login',toggle:'हिंदी',eyebrow:'A place of faith & belonging',hero:'At Baba Ramdev Mandir Raipur Hisar, every prayer is welcome, every visitor is family, and every act of seva brings us closer together.',plan:'Plan your visit ↗',today:"View today's darshan →",aboutLabel:'01 / Our temple',aboutEyebrow:'A living tradition',aboutTitle:'Rooted in devotion.\nOpen to all.',aboutLink:'Discover our story ↗',darshanLabel:'02 / Daily rhythm',darshanEyebrow:'Come as you are',darshanTitle:'Moments that\nbring us home.',darshanCopy:'Join us for darshan, aarti, and the simple joy of being together in prayer.',sevaLabel:'03 / Offerings',sevaEyebrow:'Make a difference',sevaTitle:'Seva is prayer\nin action.',visitLabel:'04 / Find your way',visitTitle:'Your next quiet\nmoment awaits.',address:'Address',phone:'Call us',email:'Write to us',directions:'Get directions ↗',footer:'A sacred space for prayer, community, and peace.',access:'Trustee access',panel:'Temple admin',panelNote:'Sign in to keep your temple details current.',signIn:'Sign in →'},hi:{top:'प्रतिदिन प्रातः 5:30 से रात्रि 9:00 बजे तक खुले',nav:['हमारे बारे में','दर्शन','सेवा','हमसे मिलें'],admin:'◈ व्यवस्थापक लॉगिन',toggle:'English',eyebrow:'आस्था और अपनत्व का स्थान',hero:'बाबा रामदेव मंदिर रायपुर हिसार में हर प्रार्थना का स्वागत है, हर आगंतुक हमारा परिवार है और सेवा का हर कार्य हमें एक-दूसरे के करीब लाता है।',plan:'दर्शन की योजना ↗',today:'आज का दर्शन देखें →',aboutLabel:'01 / हमारा मंदिर',aboutEyebrow:'एक जीवंत परंपरा',aboutTitle:'भक्ति में जड़ें।\nसबके लिए खुला।',aboutLink:'हमारी कहानी जानें ↗',darshanLabel:'02 / दैनिक समय',darshanEyebrow:'जैसे हैं वैसे आएं',darshanTitle:'वे पल जो\nहमें घर लाते हैं।',darshanCopy:'दर्शन, आरती और प्रार्थना में साथ होने की सरल खुशी के लिए हमारे साथ जुड़ें।',sevaLabel:'03 / सेवाएं',sevaEyebrow:'बदलाव लाएं',sevaTitle:'सेवा ही प्रार्थना है\nकार्य रूप में।',visitLabel:'04 / अपना रास्ता खोजें',visitTitle:'आपका अगला शांत\nपल आपका इंतजार कर रहा है।',address:'पता',phone:'फोन करें',email:'ईमेल करें',directions:'दिशा-निर्देश ↗',footer:'प्रार्थना, समुदाय और शांति का पवित्र स्थान।',access:'ट्रस्टी प्रवेश',panel:'मंदिर व्यवस्थापक',panelNote:'मंदिर की जानकारी अपडेट करने के लिए साइन इन करें।',signIn:'साइन इन करें →'}};
function setTranslatedText(selector,value){const element=document.querySelector(selector);if(element)element.textContent=value;}
function translateSite(){const t=translations[language]; document.documentElement.lang=language==='hi'?'hi':'en'; document.title=language==='hi'?'बाबा रामदेव मंदिर रायपुर हिसार':'Baba Ramdev Mandir Raipur Hisar'; $('topHours').textContent=t.top; $('languageToggle').textContent=t.toggle; $('languageToggle').setAttribute('aria-label',language==='hi'?'भाषा बदलें':'Change language'); setTranslatedText('.desktop-nav a:nth-child(1)',t.nav[0]); setTranslatedText('.desktop-nav a:nth-child(2)',t.nav[1]); setTranslatedText('.desktop-nav a:nth-child(3)',t.nav[2]); setTranslatedText('.desktop-nav a:nth-child(4)',t.nav[3]); $('adminOpen').textContent=t.admin; setTranslatedText('.hero .eyebrow',t.eyebrow); setTranslatedText('.hero-actions .button',t.plan); setTranslatedText('.hero-actions .text-link',t.today); setTranslatedText('#about .section-label',t.aboutLabel); setTranslatedText('#about .eyebrow',t.aboutEyebrow); setTranslatedText('#about h2',t.aboutTitle); setTranslatedText('#about .arrow-link',t.aboutLink); setTranslatedText('#darshan .section-label',t.darshanLabel); setTranslatedText('#darshan .eyebrow',t.darshanEyebrow); setTranslatedText('#darshan h2',t.darshanTitle); setTranslatedText('#darshan .darshan-intro>p:last-child',t.darshanCopy); setTranslatedText('#seva .section-label',t.sevaLabel); setTranslatedText('#seva .eyebrow',t.sevaEyebrow); setTranslatedText('#seva h2',t.sevaTitle); setTranslatedText('#visit .eyebrow',t.visitLabel); setTranslatedText('#visit h2',t.visitTitle); setTranslatedText('#visit .contact-details div:nth-child(1) span',t.address); setTranslatedText('#visit .contact-details div:nth-child(2) span',t.phone); setTranslatedText('#visit .contact-details div:nth-child(3) span',t.email); setTranslatedText('#mapLink',t.directions); setTranslatedText('footer p',t.footer); setTranslatedText('#loginView .eyebrow',t.access); setTranslatedText('#loginView h2',t.panel); setTranslatedText('.panel-note',t.panelNote); setTranslatedText('#loginForm button',t.signIn); render(); }
function translateRemaining(){const hindi=language==='hi'; const text=hindi?{caption:'आज दर्शन के लिए खुला है',aboutText:'हमारा मंदिर प्रार्थना, आत्मचिंतन और समुदाय के लिए एक शांत स्थान है। सेवा और प्रेम से बना यह स्थान हर उस व्यक्ति का स्वागत करता है जो शांति का एक पल खोज रहा है।',sevaNames:['अन्नदान','मंदिर सेवा','उत्सव सहयोग'],sevaCopies:['भोजन अर्पित करें और समुदाय के साथ पोषण की गर्माहट साझा करें।','इस पवित्र स्थान को सुंदर, स्वागत योग्य और जीवंत बनाए रखने में मदद करें।','हमारे वार्षिक उत्सवों की भक्ति, संगीत और रंगों का हिस्सा बनें।'],visitHeading:'आपका अगला शांत पल आपका इंतजार कर रहा है।',footerCredit:'द्वारा निर्मित: मनोज जांगड़ा, रायपुर',copyright:'© 2026 बाबा रामदेव सेवा ट्रस्ट',made:'द्वारा निर्मित: मनोज जांगड़ा, रायपुर',labels:['मंदिर का नाम','स्वागत संदेश','मंदिर के बारे में','पता','फोन','ईमेल','गूगल मैप लिंक'],update:'विवरण अपडेट करें',signed:'साइन इन है',signout:'साइन आउट',save:'परिवर्तन सेव करें →'}:{caption:'Darshan is open today',aboutText:data.about,sevaNames:['Annadanam','Temple care','Festival support'],sevaCopies:['Offer a meal and share the warmth of nourishment with our community.','Help us keep this sacred space beautiful, welcoming, and alive.','Be part of the music, color, and devotion of our annual celebrations.'],visitHeading:'Your next quiet moment awaits.',footerCredit:'Made by Manoj Jangra, Raipur',copyright:'© 2026 Baba Ramdev Seva Trust',made:'Made by Manoj Jangra, Raipur',labels:['Temple name','Welcome message','About the temple','Address','Phone','Email','Google Maps link'],update:'Update details',signed:'Signed in',signout:'Sign out',save:'Save changes →'}; setTranslatedText('.image-caption span:nth-child(2)',text.caption); setTranslatedText('#aboutCopy',text.aboutText); document.querySelectorAll('.seva-list article h3').forEach((element,index)=>element.textContent=text.sevaNames[index]); document.querySelectorAll('.seva-list article p').forEach((element,index)=>element.textContent=text.sevaCopies[index]); setTranslatedText('#visit h2',text.visitHeading); setTranslatedText('.footer-bottom span:first-child',text.copyright); setTranslatedText('.footer-bottom span:last-child',text.made); setTranslatedText('#editorView .eyebrow',text.signed); setTranslatedText('#editorView h2',text.update); setTranslatedText('#logoutButton',text.signout); setTranslatedText('#editorForm button',text.save); document.querySelectorAll('#editorForm label').forEach((label,index)=>{const input=label.querySelector('input,textarea'); if(input)label.childNodes[0].textContent=text.labels[index]+' ';}); }
$('languageToggle').addEventListener('click',()=>{language=language==='en'?'hi':'en';localStorage.setItem('jaiBabaLanguage',language);translateSite();translateRemaining();});
function translateHeroTitle(){ $('heroTitle').innerHTML=language==='hi'?'खुले दिल से आएं।<br><em>शांति लेकर जाएं।</em>':'Come with an open heart.<br><em>Leave with peace.</em>'; }
$('languageToggle').addEventListener('click',()=>translateHeroTitle());
translateSite(); translateRemaining(); translateHeroTitle();
