const defaultData = {name:'Baba Ramdev Mandir Raipur Hisar', welcome:'At Baba Ramdev Mandir Raipur Hisar, every prayer is welcome, every visitor is family, and every act of seva brings us closer together.', about:'Our mandir is a quiet corner for prayer, reflection, and community. Built with love and sustained through seva, we welcome families, elders, children, and every soul seeking a moment of stillness.', address:'4RWC+X87, Dhani Raipur, Hisar, Haryana 125044', phone:'+91 00000 00000', email:'hello@jaibabamandir.org', map:'https://maps.app.goo.gl/pNMX7ZAJRMEHQtE5A'};
const schedule = [['Mangala Aarti','5:30 AM'],['Morning Darshan','6:00 AM - 12:00 PM'],['Madhyanna Aarti','12:00 PM'],['Evening Darshan','4:00 PM - 8:30 PM'],['Shej Aarti','9:00 PM']];
let data = JSON.parse(localStorage.getItem('jaiBabaTemple')) || defaultData;
if (data.name === 'Shri Jai Baba' || data.name === 'Shri Jai Baba Mandir') data.name = defaultData.name;
if (data.welcome && data.welcome.includes('Shri Jai Baba Mandir')) data.welcome = defaultData.welcome;
if (data.address === 'Your temple address\nCity, State, PIN' || data.address === 'Your temple addressCity, State, PIN') data.address = defaultData.address;
const $ = id => document.getElementById(id);
function render(){ $('brandName').textContent=data.name; $('footerName').textContent=data.name; $('heroCopy').textContent=data.welcome; $('aboutCopy').textContent=data.about; $('address').innerHTML=data.address.replace(/\n/g,'<br>'); $('phone').textContent=data.phone; $('email').textContent=data.email; $('mapLink').href=data.map; $('schedule').innerHTML=schedule.map(([label,time])=>`<div class="schedule-row"><strong>${label}</strong><span>${time}</span></div>`).join(''); }
function openPanel(){ $('overlay').classList.add('active'); $('adminPanel').classList.add('open'); $('adminPanel').setAttribute('aria-hidden','false'); }
function closePanel(){ $('overlay').classList.remove('active'); $('adminPanel').classList.remove('open'); $('adminPanel').setAttribute('aria-hidden','true'); }
function showEditor(){ $('loginView').hidden=true; $('editorView').hidden=false; $('editName').value=data.name; $('editWelcome').value=data.welcome; $('editAbout').value=data.about; $('editAddress').value=data.address; $('editPhone').value=data.phone; $('editEmail').value=data.email; $('editMap').value=data.map; }
$('schedule').innerHTML=''; render();
$('adminOpen').addEventListener('click',openPanel); $('adminClose').addEventListener('click',closePanel); $('overlay').addEventListener('click',closePanel); $('menuToggle').addEventListener('click',()=>document.querySelector('.desktop-nav').classList.toggle('mobile-open'));
$('loginForm').addEventListener('submit',event=>{event.preventDefault(); const email=$('loginEmail').value.trim().toLowerCase(); const password=$('loginPassword').value; if(email==='admin@jaibabaramdave.org'&&password==='jai baba ri'){ $('loginError').textContent=''; showEditor(); } else $('loginError').textContent='That email or password is not recognised.'; });
$('editorForm').addEventListener('submit',event=>{event.preventDefault(); data={name:$('editName').value.trim(),welcome:$('editWelcome').value.trim(),about:$('editAbout').value.trim(),address:$('editAddress').value.trim(),phone:$('editPhone').value.trim(),email:$('editEmail').value.trim(),map:$('editMap').value.trim()}; localStorage.setItem('jaiBabaTemple',JSON.stringify(data)); render(); $('saveStatus').textContent='Changes saved to this browser.'; setTimeout(()=>$('saveStatus').textContent='',3000); });
$('logoutButton').addEventListener('click',()=>{ $('editorView').hidden=true; $('loginView').hidden=false; $('loginForm').reset(); });
